### ISSUE TITLE
Error message doesn’t have it HTML content parsed/displayed

### ISSUE THREAD

**Issue by Galixte** [rmcgirr83/contactadmin#11]
Hi @rmcgirr83,

- if I activate the extension option to send email,
- if I disable the global phpBB option to send mail on the forum,
- if I send the form from the /contactadmin  page,
- It displays an error message: “There is an error with the configuration of the Contact  Administration.<br />The extension is set to send an email but the configuration isn’t setup to send emails.  Please notify the administrator or webmaster: <a href="mailto:forum@localhost.fr">mailto:forum@localhost.fr</a>” that it content isn’t parsed/displayed.

![contact admin error message html content isn t parsed](https://user-images.githubusercontent.com/7478287/43178992-b5d4d05a-8fd0-11e8-870c-572658b30fce.png)

**Comment by rmcgirr83** [comment]
https://github.com/rmcgirr83/contactadmin/commit/7c5d874a45f08aea18070d4e331aaf4e43e92fef

**Comment by Galixte** [comment]
Thanks.
