### ISSUE TITLE
Use "Contact E-Mail" info to send the emails there

### ISSUE THREAD

**Issue by LukasThyWalls** [rmcgirr83/contactadmin#12]
Hello

I was wondering if it's possible to change a detail of this extension.

When you set to use email, you can (A) send the form to all the admins emails, (B) send the form to the founder (if you check that option).

However, the built in contact form (at least in PHPBB 3.3.0) use email entered in the "Contact Email" info in ACP -> Client Communication -> Email Configuration (And Contact Name)

Is possible to use this (As a third option or replacing the all admins option)? Or maybe put a single email to send the contacts?

Thanks.

**Comment by rmcgirr83** [comment]
Not easily, no.

**Comment by LukasThyWalls** [comment]
Oh, Ok!

Thanks!

**Comment by rmcgirr83** [comment]
Please test

https://github.com/rmcgirr83/contactadmin/tree/1.1.13

**Comment by LukasThyWalls** [comment]
Tested. Seems working fine.
