### ISSUE TITLE
Does it work with 3.3?

### ISSUE THREAD

**Issue by justintuijl** [rmcgirr83/contactadmin#13]
Does it work with 3.3?

**Comment by rmcgirr83** [comment]
Try it and see.  Not like your forum is going to blow up or anything.
https://github.com/rmcgirr83/contactadmin/blob/master/.travis.yml#L36

**Comment by justintuijl** [comment]
It doesn't work unfortunately

**Comment by rmcgirr83** [comment]
It works perfectly unless you don't know how to install extensions

**Comment by justintuijl** [comment]
I've had that extension on there for a year or two. I activated it again
after upgrade to 3.3 like you suggested, but it just doesn't show up like
it did before.

**Comment by rmcgirr83** [comment]
Provide step by step details of what you are doing

**Comment by justintuijl** [comment]
I was running phpbb 3.2.3 with Contact Admin 1.1.10
I deactivated all extensions.
Upgraded to 3.3
Updated extensions that needed it and activated them.
Tried to activate Contact Admin 1.1.10
Message comes up " The selected extension cannot be enabled, please verify
the extension’s requirements."
(The standard built it contact form was switched off at the time. But I
have now turned it on do to Contact Admin 1.1.10 not working)
Hope that helps.

**Comment by rmcgirr83** [comment]
That isn't from this repo. That's from phpbb. The extension in this repo
works on 3.3.

**Comment by justintuijl** [comment]
Ok, thank you, I'll download from here then. Cheers. And thanks for the
extensions you produce, I use a lot of your ones.
