### ISSUE TITLE
No email sent to founders

### ISSUE THREAD

**Issue by wads24** [rmcgirr83/contactadmin#14]
I tested newest version, no email is sent to founders. All permissions set to yes

**Comment by Doelli** [comment]
I can confirm this issue

**Comment by rmcgirr83** [comment]
Anything in the logs?

**Comment by Doelli** [comment]
I am sorry but the it was a 
PEBCAK! :-)
Thank you for this great MOD!

**Comment by rmcgirr83** [comment]
So not an issue, issue closed.
