### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by fantabaffo** [rmcgirr83/contactadmin#15]
Hallo,
after installing the estension, my forum has become unreachable: I can only use admin panel.
If I uninstall the extension, the issue remains. Any suggestions?

Thanks a lot, 
Fantabaffo.

This is the error message:

> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid repository file' in /membri/hifi/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/Repository.php:30 Stack trace: #0 /membri/hifi/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/RepositoryCollection.php(22): s9e\TextFormatter\Plugins\BBCodes\Configurator\Repository->__construct('/membri/hifi/ve...', Object(s9e\TextFormatter\Plugins\BBCodes\Configurator\BBCodeMonkey)) #1 /membri/hifi/vendor/s9e/text-formatter/src/Configurator.php(7374): s9e\TextFormatter\Plugins\BBCodes\Configurator\RepositoryCollection->normalizeValue('/membri/hifi/ve...') #2 /membri/hifi/vendor/s9e/text-formatter/src/Configurator.php(7344): s9e\TextFormatter\Configurator\Collections\NormalizedCollection->set('default', '/membri/hifi/ve...') #3 /membri/hifi/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator.php(37): s9e\TextFormatter\Configurator\Collections\NormalizedCollection->add('default', '/membri/hifi/ve...') #4 /membri/hifi/vendor/s9e/text- in /membri/hifi/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/Repository.php on line 30

**Comment by rmcgirr83** [comment]
Has to do with this
`/membri/hifi/vendor/s9e/`
