### ISSUE TITLE
Standard Contact icon in footer still visible when 1.1.12 is enabled

### ISSUE THREAD

**Issue by haiopaio** [rmcgirr83/contactadmin#16]
The standard Contact icon in the footer still visible when 1.1.12 is enabled. PhpBB3.3.2 German, OrangeBBEs Style.
The same happens with Prosilver Style and British English selected.

![Bildschirmfoto 2020-11-21 um 10 50 04](https://user-images.githubusercontent.com/41449770/99874406-12a2d380-2be8-11eb-98d7-8a706b3b2511.jpg)

**Comment by rmcgirr83** [comment]
So don't use that version as it's out of date.
