### ISSUE TITLE
Hide GDPR checkbox for registered users?

### ISSUE THREAD

**Issue by Infarinato** [rmcgirr83/contactadmin#18]
(Not really an issue _per se_, more like a feature request… 😊)

I was pleased to see the extension now caters for GDPR-type confirmation, but was wondering whether the relevant checkbox could be hidden for registered users, as those should have already agreed to the terms of the board’s privacy policy.

Also, as it stands, the checkbox label text doesn’t make complete sense for them, as they don’t need to enter any name or e-mail address… 😉

**Comment by rmcgirr83** [comment]
Try
https://github.com/rmcgirr83/contactadmin/commit/47315027bc685b940a6df02cab2d30fd88fce016
