### ISSUE TITLE
Message will not sended on PHP 8.0

### ISSUE THREAD

**Issue by Doelli** [rmcgirr83/contactadmin#19]
Today i switched from PHP 7.4 to PHP 8.0.
After that i tried to send serveral Test Messages via Contact Admin 1.3.7 but this was not sended all times.
So i swichted back to PHP 7.4 and i tried it again. All messages where sended / received.

Currently i use phpBB 3.3.3

Kind Regards

**Comment by rmcgirr83** [comment]
Do you get normal emails from the forum? Any errors in the logs either in the acp or the server?

**Comment by Doelli** [comment]
You´re right!

I´d registred a Testuser on my phpBB 3.3.3 while i running PHP 8.0.
No Mail was sendet. It seems a problem with phpBB 3.3.3.

**Comment by rmcgirr83** [comment]
Closing as not reproducible.
