### ISSUE TITLE
I have strange problem with current version and PHP 3.1.10

### ISSUE THREAD

**Issue by warlock9k** [rmcgirr83/contactadmin#2]
I try to send a test e-mail and got such exception stack:

[phpBB Debug] PHP Notice: in file [ROOT]/ext/rmcgirr83/contactadmin/core/contactadmin.php on line 426: Use of undefined constant CONTACT_METHOD_EMAIL - assumed 'CONTACT_METHOD_EMAIL'
[phpBB Debug] PHP Notice: in file [ROOT]/ext/rmcgirr83/contactadmin/core/contactadmin.php on line 430: Use of undefined constant CONTACT_METHOD_PM - assumed 'CONTACT_METHOD_PM'
[phpBB Debug] PHP Notice: in file [ROOT]/ext/rmcgirr83/contactadmin/core/contactadmin.php on line 225: Use of undefined constant CONTACT_METHOD_EMAIL - assumed 'CONTACT_METHOD_EMAIL'
[phpBB Debug] PHP Notice: in file [ROOT]/ext/rmcgirr83/contactadmin/core/contactadmin.php on line 250: Undefined variable: phpEx
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 5337: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3925)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 5337: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3925)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 5337: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3925)

Do someone have ideas what it could be?

**Comment by rmcgirr83** [comment]
What version of this extension are you using?

**Comment by warlock9k** [comment]
I'm using the last one from here. And when I tried version from here https://www.phpbb.com/customise/db/extension/contact_admin, there was another error: "The user Anonymous tried to use the Contact Admin Extension at <forum name> to send a Email, but there are no Administrators that allow Emails by users. Please enter the Contact Bot Configuration in the Admin Panel for the forum <adress> and choose the “Board Founder” option".

**Comment by rmcgirr83** [comment]
Fixed the first error (made a push).  Concerning the other, it is obvious.  None of the administrators on the forum have the "Users can contact me via email" in the UCP set to yes.

**Comment by warlock9k** [comment]
Thanks! Now it works.
And what's about second question - is it possible to send letter to the board "Contact email address"? I think that it's not a good idea to send emails to the administrator's personal emails.

**Comment by rmcgirr83** [comment]
No, that isn't possible without re-writing a lot of the code.  You could always use the forum post option or the PM option.

**Comment by warlock9k** [comment]
I understand thank you!
