### ISSUE TITLE
SQL ERROR [ mysqli ]

### ISSUE THREAD

**Issue by wads24** [rmcgirr83/contactadmin#3]
I am using 3.2 version of phpBB, and Contact Admin 1.1.1

I have it set to post in a forum, and when a user is signed into the site it works great, but if they are not logged into the forum they get this error when submitting the form.

> General Error
> SQL ERROR [ mysqli ]
> 
> Column 'user_ip' cannot be null [1048]
> 
> An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

**Comment by rmcgirr83** [comment]
user_ip doesn't have anything to do with this as that is located within the users table and not the post table when submitting a post via this extension.

**Comment by rmcgirr83** [comment]
Further, in the future either post your issue here OR in the support section of the extension at phpBB.  Not both please.
