### ISSUE TITLE
Packagist Support (Improvement)

### ISSUE THREAD

**Issue by Crizz0** [rmcgirr83/contactadmin#5]
Hi,

to use/maintain your extension with composer, it would be great if you would support https://packagist.org/

Regards

**Comment by rmcgirr83** [comment]
Done, probably not correctly though.  Can't seem to get packagist to auto-update the repo.

**Comment by Crizz0** [comment]
You need to go to:
https://github.com/Crizz0/phpbb3-about-us/settings/installations --> Add service --> Packagist --> and add your Username + Token from Packagist (which you'll find on the top of here: https://packagist.org/profile/ ). Afterwards press "test service" on the right top corner. 

That'll do it. :)

**Comment by rmcgirr83** [comment]
Done, thanks!
