### ISSUE TITLE
Require of phpbb/phpbb makes problems with composer installation

### ISSUE THREAD

**Issue by Crizz0** [rmcgirr83/contactadmin#6]
Hi,

I've tried to install your extension via composer.

I've added `"rmcgirr83/contactadmin": "1.1.*"` to my phpBB composer.json and run ` ../composer.phar update`, but then phpBB tries to install the extension and your extension tries to install phpBB, which won't work.

This led to:
```
$ ../composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpbb/phpbb No version set (parsed as 1.0.0) -> satisfiable by phpbb/phpbb[No version set (parsed as 1.0.0)].
    - rmcgirr83/contactadmin 1.1.0 requires phpbb/phpbb >=3.1.3, <3.4 -> satisfiable by phpbb/phpbb[3.1.3, 3.1.4].
    - Can only install one of: phpbb/phpbb[3.1.3, No version set (parsed as 1.0.0)].
    - Can only install one of: phpbb/phpbb[3.1.4, No version set (parsed as 1.0.0)].
    - Installation 
```

I think you should remove this part: https://github.com/rmcgirr83/contactadmin/blob/master/composer.json#L22 and online keep line #30

With reference to: https://area51.phpbb.com/docs/dev/31x/extensions/tutorial_basics.html#composer-json

Regards

PS:  Tagging the versions here on github, would be nice, too. :) 1.1.1 and higher is missing. :(

**Comment by rmcgirr83** [comment]
So the question then is why wasn't this pointed out during validation?  Doesn't installing via CLI require this?

**Comment by Crizz0** [comment]
The cli is different to composer. It is just the same function, which will be activated when you click install in ACP. Composer downloads the extension, updates it and removes unused files, but does not click the install button.

**Comment by paul999** [comment]
@rmcgirr83 Because it is added by titania, so we don't see that it exists already when you submit it :).
You should, at least untill 3.3, not add the phpbb/phpbb requirment, but only have it in soft-require if you submit your extension to packagist.

**Comment by rmcgirr83** [comment]
Okies and thanks for the explanation.  Fixed
