### ISSUE TITLE
Release tags not up to date

### ISSUE THREAD

**Issue by Crizz0** [rmcgirr83/contactadmin#9]
Hi,

at the moment the release tags are not up to date: https://github.com/rmcgirr83/contactadmin/releases

The latest version should be 1.1.5. That makes it hard to use composer to install your extension, because only dev-master is a bit dangerous. One wrong push from you/or other, might kill my live website on next `./composer.phar update`. :( 

Would be glad, if you would use the tagging again.

Regards

**Comment by rmcgirr83** [comment]
As it is for a phpBB forum, the release updates should come from the CDB IMHO.

**Comment by Crizz0** [comment]
It has nothing to do with CDB. 

With composer (which downloads all extensions for me on the server), is define something like:

`"phpbbde/movemessage": "^1.0",` 

Which will download the latest release from that extension in version 1.0.x. 

When i do something like:
`"rmcgirr83/contactadmin": "^1.1",`
I grap the version 1.1.0, because this is the latest tagged here. Because github/composer cannot find any newer version than that. 1.1.5 is not found. 

So all asked for is: - tag the release here, when you decide you make a 1.1.6 and upload a new version with that files to the CDB, so I can automatically update to that. With the current, I grap you current master branch, will could lead to a extension failure, when you commit something broken, which can always happen to a dev-branch.

Regards
